import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ChevronUp, UserCircle } from "lucide-react";
import { Sidebar, SidebarContent, SidebarFooter, SidebarGroup, SidebarGroupContent, SidebarHeader, SidebarMenu, SidebarMenuButton, SidebarMenuItem, SidebarTrigger, } from "@/components/ui/sidebar";
import { Link, useLocation } from "react-router-dom";
export function AppSidebar({ menuItems }) {
    const { pathname } = useLocation();
    return (_jsxs(Sidebar, { variant: "sidebar", collapsible: "icon", className: "relative", children: [_jsx(SidebarTrigger, { className: "absolute group-data-[collapsible=icon]:hidden rounded-md top-5 right-3 z-50" }), _jsx(SidebarHeader, { className: "ghost-border pb-1", children: _jsx(SidebarMenu, { children: _jsx(SidebarMenuItem, { children: _jsx(SidebarMenuButton, { size: "lg", className: "cursor-default hover:bg-transparent px-0", children: _jsxs("div", { className: "flex flex-col gap-0.5 leading-none w-full relative overflow-hidden", children: [_jsxs("div", { className: "flex flex-col transition-all duration-300 group-data-[collapsible=icon]:opacity-0 group-data-[collapsible=icon]:invisible", children: [_jsx("span", { className: "font-display font-semibold tracking-tightest whitespace-nowrap [mask-image:linear-gradient(to_right,black_80%,transparent_100%)]", children: "Admin Panel LUXE" }), _jsx("span", { className: "text-[10px] text-on-surface-variant", children: "Management" })] }), _jsx("div", { className: "absolute inset-1 flex items-center justify-center opacity-0 invisible transition-all duration-300 group-data-[collapsible=icon]:opacity-100 group-data-[collapsible=icon]:visible", children: _jsx("span", { className: "font-display font-bold tracking-tightest text-primary", children: _jsx(SidebarTrigger, {}) }) })] }) }) }) }) }), _jsx(SidebarContent, { children: _jsx(SidebarGroup, { children: _jsx(SidebarGroupContent, { children: _jsx(SidebarMenu, { className: "mt-3", children: menuItems.map((item) => {
                                const isActive = pathname === item.url;
                                return (_jsx(SidebarMenuItem, { children: _jsxs(SidebarMenuButton, { className: `relative flex items-center gap-3 hover:bg-on-surface-variant/20 hover:text-primary transition-all duration-300 p-2 h-12 group-data-[collapsible=icon]:p-0 my-1 rounded-md ${isActive ? "bg-surface-container-low text-primary" : ""}`, children: [_jsx(item.icon, { size: 18, className: `ml-1` }), _jsx(Link, { to: item.url, className: `absolute inset-0` }), _jsx("span", { children: item.title }), pathname === item.url && (_jsx("div", { className: "group-data-[collapsible=icon]:hidden inline-block -mr-2 ml-auto w-1 h-[200%] bg-signature-gradient" }))] }) }, item.title));
                            }) }) }) }) }), _jsx(SidebarFooter, { className: "border-t ghost-border pt-4", children: _jsx(SidebarMenu, { children: _jsx(SidebarMenuItem, { children: _jsxs(SidebarMenuButton, { size: "lg", className: "data-[state=open]:bg-sidebar-accent", children: [_jsx(UserCircle, { className: "size-5" }), _jsxs("div", { className: "flex flex-col items-start text-sm", children: [_jsx("span", { className: "font-medium text-on-surface", children: "Omar Ali" }), _jsx("span", { className: "text-xs text-on-surface-variant", children: "Admin Account" })] }), _jsx(ChevronUp, { className: "ml-auto size-4 text-on-surface-variant" })] }) }) }) })] }));
}
export default AppSidebar;
