import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link, Outlet, useLocation } from "react-router-dom";
import { AnimatePresence, motion } from "framer-motion";
import { Button } from "../ui/button";
const AuthLayout = () => {
    const { pathname } = useLocation();
    return (_jsxs("section", { className: "relative min-h-screen overflow-hidden bg-surface py-2 px-2 xs:px-8", children: [_jsxs("header", { className: "flex items-center justify-between relative z-10", children: [_jsx(Link, { to: "/", children: _jsx("h1", { className: "text-xl font-bold", children: "LUXE" }) }), pathname === "/auth/login" ? (_jsxs("div", { children: [_jsx("p", { className: "inline-block text-on-surface/50 text-body-sm mr-2", children: "Not a member?" }), _jsx(Link, { to: "signup", children: _jsx(Button, { size: "sm", variant: "outline", className: "text-on-surface", children: "Sign Up" }) })] })) : (_jsxs("div", { children: [_jsx("p", { className: "inline-block text-on-surface/50 text-body-sm mr-2", children: "Already a member?" }), _jsx(Link, { to: "login", children: _jsx(Button, { size: "sm", variant: "outline", children: "Log In" }) })] }))] }), _jsxs(AnimatePresence, { mode: "popLayout", children: [pathname === "/auth/login" ? (_jsx(motion.div, { initial: { opacity: 0, x: -30 }, animate: { opacity: 1, x: 0 }, exit: { opacity: 0, x: -30 }, transition: { duration: 0.7 }, className: "\r\n      absolute block top-0 left-0 w-1/2 h-full \r\n      [mask-image:linear-gradient(to_right,black_-10%,transparent_100%)]\r\n      bg-[url('/bg2.png')] bg-no-repeat \r\n      bg-[length:cover] \r\n      bg-[position:center]  \r\n      " }, "login-image")) : (_jsx(motion.div, { initial: { opacity: 0, x: 30 }, animate: { opacity: 1, x: 0 }, exit: { opacity: 0, x: 30 }, transition: { duration: 0.7 }, className: "\r\n        absolute block top-0 right-0 w-1/2 h-full \r\n        [mask-image:linear-gradient(to_left,black_-10%,transparent_100%)]\r\n        bg-[url('/bg2.png')] bg-no-repeat \r\n        bg-[length:cover] \r\n        bg-[position:center]  \r\n        " }, "signup-image")), _jsx(Outlet, {})] })] }));
};
export default AuthLayout;
