import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ArrowRight } from "lucide-react";
import { Link } from "react-router-dom";
import { Button } from "../ui/button";
import { useProduct } from "@/hooks/useProduct";
const Hero = () => {
    const { data } = useProduct("69d2a67139868d6fb9dbad3a");
    return (_jsxs("section", { className: "relative content-center overflow-hidden bg-surface-container-low min-h-screen ", children: [_jsx("div", { className: "absolute top-5 right-5 w-[250px] h-[250px] bg-primary/30 rounded-full blur-[120px]" }), _jsx("div", { className: "absolute bottom-5 left-5 w-[250px] h-[250px] bg-secondary/30 rounded-full blur-[120px]" }), _jsxs("div", { className: "px-4 mx-auto flex sm:flex-row flex-col my-16 sm:my-0 sm:items-center justify-between gap-4 relative", children: [_jsxs("div", { children: [_jsxs("h1", { className: "text-4xl sm:text-display-lg font-bold", children: ["Redefining the", _jsx("br", {}), _jsx("span", { className: "bg-signature-gradient bg-clip-text text-transparent", children: "Art of Luxury" })] }), _jsx("p", { className: "text-body-sm text-on-surface-variant my-8 max-w-sm", children: "Discover a curated collection where timeless craftsmanship meets modern sophistication. Elevate your presence with LUXE." }), _jsx("div", { children: _jsx(Link, { to: "/products", children: _jsx(Button, { variant: "default", className: "bg-signature-gradient !text-surface text-body-sm px-5 py-3", children: "Explore Collection" }) }) })] }), _jsxs("div", { className: "sm:w-1/2 aspect-[4/5] sm:aspect-[3/4] md:aspect-[4/5] max-h-[90vh] relative overflow-hidden", children: [_jsx("img", { src: data?.images[0], alt: data?.images[0], className: "h-full w-full object-cover object-center mx-auto rounded-lg ghost-border !border-4" }), _jsxs("div", { className: "glass rounded-lg absolute bottom-3 left-3 w-[90%] p-5", children: [_jsx("span", { className: "uppercase text-body-sm tracking-widest text-primary", children: "From The Owner" }), _jsx("h2", { className: "text-2xl line-clamp-1", children: data?.name }), _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("p", { className: "tracking-widest text-on-surface-variant", children: ["$", data?.price] }), _jsx(Link, { to: "/product/69d2a67139868d6fb9dbad3a", children: _jsx(ArrowRight, { className: "text-secondary" }) })] })] })] })] })] }));
};
export default Hero;
