import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from "framer-motion";
const ComingSoon = () => {
    // Text Animation Settings
    const fadeInUp = {
        initial: { opacity: 0, y: 20 },
        animate: { opacity: 1, y: 0 },
        transition: { duration: 0.8, ease: [0.16, 1, 0.3, 1] },
    };
    return (_jsxs("div", { className: "relative min-h-screen bg-surface font-body text-on-surface overflow-hidden flex flex-col items-center justify-center p-4 xs:p-6", children: [_jsx("div", { className: "absolute top-[-10%] left-[-10%] w-[50%] h-[50%] bg-primary-dim opacity-10 blur-[120px] rounded-full" }), _jsx("div", { className: "absolute bottom-[-10%] right-[-10%] w-[40%] h-[40%] bg-secondary opacity-5 blur-[100px] rounded-full" }), _jsxs("div", { className: "relative z-10 w-full max-w-2xl text-center", children: [_jsx(motion.div, { initial: { opacity: 0, scale: 0.9 }, animate: { opacity: 1, scale: 1 }, transition: { duration: 1 }, className: "mb-12", children: _jsxs("h2", { className: "font-display text-[1.5rem] tracking-[0.4em] uppercase text-primary", children: ["Luxe", " ", _jsx("span", { className: "text-on-surface-variant font-light text-sm tracking-widest block mt-1", children: "Premium Experience" })] }) }), _jsxs(motion.h1, { ...fadeInUp, className: "font-display text-display-lg mb-6 bg-signature-gradient bg-clip-text text-transparent", children: ["The Future of Luxury ", _jsx("br", {}), " is Coming."] }), _jsx(motion.p, { ...fadeInUp, transition: { delay: 0.2, duration: 0.8 }, className: "text-on-surface-variant text-lg mb-12 max-w-md mx-auto leading-relaxed", children: "We are refining a unique experience tailored to your taste. Stay tuned for our official launch into the world of true luxury." }), _jsxs(motion.div, { ...fadeInUp, transition: { delay: 0.6, duration: 0.8 }, className: "mt-20 flex justify-center gap-8", children: [_jsxs("div", { className: "flex flex-col items-center", children: [_jsx("span", { className: "text-primary font-display text-2xl", children: "05" }), _jsx("span", { className: "text-on-surface-variant text-xs uppercase tracking-widest", children: "Days" })] }), _jsx("div", { className: "w-[1px] h-10 bg-outline-variant mt-2" }), _jsxs("div", { className: "flex flex-col items-center", children: [_jsx("span", { className: "text-primary font-display text-2xl", children: "12" }), _jsx("span", { className: "text-on-surface-variant text-xs uppercase tracking-widest", children: "Hours" })] }), _jsx("div", { className: "w-[1px] h-10 bg-outline-variant mt-2" }), _jsxs("div", { className: "flex flex-col items-center", children: [_jsx("span", { className: "text-primary font-display text-2xl", children: "48" }), _jsx("span", { className: "text-on-surface-variant text-xs uppercase tracking-widest", children: "Mins" })] })] })] }), _jsx(motion.footer, { initial: { opacity: 0 }, animate: { opacity: 1 }, transition: { delay: 1, duration: 1 }, className: "absolute bottom-8 text-on-surface-variant/30 text-body-sm tracking-widest uppercase", children: "\u00A9 2026 LUXE Premium \u2014 Minimalist Excellence" })] }));
};
export default ComingSoon;
