import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { BrowserRouter } from "react-router-dom";
import { Toaster } from "react-hot-toast";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import App from "./App";
import "./index.css";
const queryClient = new QueryClient();
createRoot(document.getElementById("root")).render(_jsx(StrictMode, { children: _jsxs(BrowserRouter, { children: [_jsx(QueryClientProvider, { client: queryClient, children: _jsx(App, {}) }), _jsx(Toaster, { position: "bottom-right", reverseOrder: true })] }) }));
